// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HelloWorld() {
  return window['go']['main']['App']['HelloWorld']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ProjectExists(arg1) {
  return window['go']['main']['App']['ProjectExists'](arg1);
}

export function ReadProject(arg1) {
  return window['go']['main']['App']['ReadProject'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
