// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:main.Project):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HelloWorld():Promise<void>;

export function ListProjects():Promise<Array<main.Project>>;

export function ProjectExists(arg1:string):Promise<boolean>;

export function ReadProject(arg1:string):Promise<main.Project>;

export function UpdateProject(arg1:main.Project):Promise<void>;
